name: Deploy React App
on:
  push:
    branches:
    - master
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint application
        run: npm run lint
  build:
    needs: [lint, test]
    strategy:
      matrix:
        node-version: [14, 16]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...